### PR TITLE
add control_p8_mynn test

### PR DESCRIPTION
**Pull request by grantfirl**
- added control_p8_mynn test
 -- uses export IMFSHALCNV = -1, export SHAL_CNV = .false.,export DO_MYNNEDMF=.true.
 -- satmedmf is set to false in default_vars.sh/export_fv3()
- added new test to rt.conf

- added satmedmf=T to default_vars.sh/export_cpl() so that tests using export_cpl will have satmedmf set as before
- edited cpld_control.nml.IN to have do_mynnedmf, shal_cnv, and satmedmf controlled by namelist vars
- set satmedmf=T to standalone tests that use cpld_control.nml.IN that don't use export_cpl to set namelist values as before

### CODE REVIEW

**Comment by grantfirl** [comment]
@joeolson42 This should do the trick for adding a new test and leaving existing tests alone. I'm testing on Hera/Intel now before asking you to merge it.

**Comment by grantfirl** [comment]
@joeolson42 It looks like these changes don't cause any additional tests to fail. Before this is merged, I'm running the new test by itself to create a baseline and check reproducibility against the new baseline. I'll report back when that's done.

**Comment by grantfirl** [comment]
@joeolson42 I'm trying to run the test with the checks for MYNN EDMF/SFC commented out in noahmpdrv.F90. I don't understand NoahMP's dependence on MYNN, though. I'm hoping that Helin or Mike can shed some light, regardless of whether the test runs or not.

**Comment by joeolson42** [comment]
We should hear back from them soon (I sent another email). As far as I know, I think this logic can be removed without any problem. The MYNN-EDMF can be run with any surface layer scheme. That should stay true when run with Noah-MP. When we hear back, let me know how you want to proceed.

**Comment by grantfirl** [comment]
@joeolson42 OK, this should be ready for merge. It looks like there were 2 other PRs merged into develop since the last time this branch was updated. Merging this PR will make https://github.com/ufs-community/ufs-weather-model/pull/1636 up-to-date.

**Review by joeolson42 — APPROVED** [review]

**Pull request merged**
